#pragma once

#define TAPPING_TERM_PER_KEY

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define CAPS_WORD_INVERT_ON_SHIFT

#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 300

#define BACKLIGHT_DEFAULT_LEVEL 2  // max 3
